# Generated by Django 2.0.5 on 2020-01-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIViewApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='id',
        ),
        migrations.AlterField(
            model_name='emp',
            name='eno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
